### ISSUE TITLE
Any reason to use a separate method to set default values for attributes. Please revisit this code.

### ISSUE THREAD

**Issue by karthikphm** [iam-aniruddha/Assignment_4#1]
https://github.com/iam-aniruddha/Assignment_4/blob/5e2009971a5646ea78c3ff0fbffc026317560e69/solution.py#L125C9-L125C32

**Comment by iam-aniruddha** [comment]
This method is designed to ensure that an Employee object has default values for its attributes in case any of them are not provided during object initialization.
The method uses the Faker module to generate random data for attributes such as emp_id, emp_name, emp_email, business_unit, and salary. If any of these attributes are not set during object creation, the generate_default_values method fills them with randomly generated data.
for e.g. - 
emp1 = Employee(emp_id=1234, emp_name="John Doe")

# Use generate_default_values to fill in the missing data
emp1.generate_default_values()

# Display the updated employee data
print("Updated Employee Details:")
print("Employee ID:", emp1.get_emp_id())
print("Employee Name:", emp1.get_emp_name())
print("Employee Email:", emp1.get_emp_email())
print("Business Unit:", emp1.get_business_unit())
print("Salary:", emp1.get_salary())
